services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm
    user: node
    command: sleep infinity
    ports:
      - "3000:3000"
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}:cached
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:11.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pass_locker
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -uroot -proot"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mariadb-data:
